site_name: PlasMol Documentation
site_description: Hybrid FDTD–RTTDDFT framework for plasmon-molecule interactions
site_author: Brinton King Eldridge
repo_url: https://github.com/kombatEldridge/PlasMol
edit_uri: edit/main/doc/docs/

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - Home: index.md
  - Getting Started:
    - About: about.md
    - Installation: installation.md
    - Usage: usage.md
    - Tutorials: tutorials.md
  - Simulations:
    - Overview: simulations/index.md
    - Classical: simulations/classical.md
    - Quantum: simulations/quantum.md
    - Hybrid PlasMol: simulations/plasmol.md
    - Fourier: simulations/fourier.md
    - Core-Hole: simulations/core_hole.md
    - Comparison: simulations/comparison.md
    - Tune: simulations/tune.md
    - NP Cross-Sections: simulations/np_abs_cross_sec.md
    - Scatter Response: simulations/scatter_response_fxn.md
    - Verify Source: simulations/verify_source.md
  - Advanced:
    - Theory & Methodology: methodology.md
    - Fourier Spectra: methodology/fourier.md
    - Effective Polarizability: methodology/effective_polarizability.md
    - Core-Hole Dynamics: methodology/core_hole.md
  - Community:
    - Contributing: contributing.md
    - Custom Drivers: custom_drivers.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true  # Allows generic $...$ delimiters
  - tables
  - attr_list

plugins:
  - search

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js  # MathJax CDN for LaTeX