site_name: PlasMol Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Tutorials: tutorials.md
  - Methodology: methodology.md
  - API Reference: api-reference.md
  - Contributing: contributing.md
  - About: about.md
theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true  # Allows generic $...$ delimiters
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js  # MathJax CDN for LaTeX